name: unsigned-to-signed
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - boost=1.74.0
  - boost-cpp=1.74.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - cairo=1.16.0
  - certifi=2022.9.24
  - cycler=0.11.0
  - expat=2.4.8
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - gettext=0.21.1
  - greenlet=1.1.2
  - icu=70.1
  - jpeg=9e
  - lcms2=2.14
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.70.2
  - libgomp=12.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.38
  - libstdcxx-ng=11.2.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libzlib=1.2.12
  - lz4-c=1.9.3
  - matplotlib-base=3.5.2
  - munkres=1.1.4
  - ncurses=6.3
  - openjpeg=2.5.0
  - openssl=3.0.7
  - packaging=21.3
  - pandas=1.4.2
  - pcre=8.45
  - pillow=9.2.0
  - pip=22.2.2
  - pixman=0.40.0
  - pthread-stubs=0.4
  - pycairo=1.21.0
  - pyparsing=3.0.9
  - python=3.9.13
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2022.6
  - readline=8.1.2
  - reportlab=3.5.68
  - setuptools=63.4.1
  - six=1.16.0
  - sqlalchemy=1.4.44
  - sqlite=3.39.3
  - tk=8.6.12
  - tzdata=2022c
  - unicodedata2=15.0.0
  - wheel=0.37.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyz2mol=0.1.2
  - xz=5.2.6
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - absl-py==1.2.0
    - aiohttp==3.8.3
    - aiosignal==1.2.0
    - async-timeout==4.0.2
    - attrs==22.1.0
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - click==8.1.3
    - contourpy==1.0.5
    - dgl==0.9.1
    - docker-pycreds==0.4.0
    - fire==0.4.0
    - fonttools==4.37.4
    - frozenlist==1.3.1
    - fsspec==2022.8.2
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.12.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.49.1
    - idna==3.4
    - importlib-metadata==4.12.0
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - lightning-utilities==0.3.0
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.1
    - multidict==6.0.2
    - networkx==2.8.6
    - numpy==1.23.3
    - oauthlib==3.2.1
    - pathtools==0.1.2
    - promise==2.3
    - protobuf==3.19.5
    - psutil==5.9.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.2
    - pytorch-lightning==1.8.1
    - pyyaml==6.0
    - rdkit==2022.3.5
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-learn==1.1.2
    - scipy==1.9.1
    - sentry-sdk==1.9.9
    - setproctitle==1.3.2
    - shortuuid==1.0.9
    - smmap==5.0.0
    - spyrmsd==0.5.2
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==2.1.0
    - threadpoolctl==3.1.0
    - torch==1.12.1
    - torch-ema==0.3
    - torchmetrics==0.9.3
    - tqdm==4.64.1
    - typing-extensions==4.3.0
    - urllib3==1.26.12
    - wandb==0.13.3
    - werkzeug==2.2.2
    - yarl==1.8.1
    - zipp==3.8.1
